# Generated by Django 3.2.7 on 2021-09-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Полное название места')),
                ('description_short', models.CharField(max_length=400, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Длинное описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, verbose_name='ID места')),
                ('title', models.CharField(max_length=200, verbose_name='Сокращенное название места')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('place_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='places.placedetails', verbose_name='Сведения о месте')),
            ],
        ),
    ]
