# Generated by Django 3.2.7 on 2021-09-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['index_number']},
        ),
        migrations.AlterField(
            model_name='image',
            name='index_number',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
