# Generated by Django 3.2.7 on 2021-09-23 11:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210923_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedetails',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Длинное описание'),
        ),
    ]
