# Generated by Django 3.2.7 on 2021-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_placedetails_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='ID места'),
        ),
        migrations.AlterUniqueTogether(
            name='placedetails',
            unique_together={('latitude', 'longitude')},
        ),
    ]
