# Generated by Django 3.2.7 on 2021-11-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210928_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedetails',
            name='description_short',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
    ]
