# Generated by Django 3.2.7 on 2021-11-02 16:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placedetails_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='index_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='К какому месту относится изображение'),
        ),
        migrations.AlterField(
            model_name='placedetails',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='placedetails',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
    ]
