# Generated by Django 3.2.7 on 2021-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20211102_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сокращенное название места'),
        ),
    ]
